# Set show log: yes or no
logshow: yes

# Set manually port
listenAddress: 0.0.0.0:3979

# Set timeout
readTimeout: 10s
writeTimeout: 10s
idleTimeout: 0
proxyClient.timeout: 60s

# DNS
dnsFallback: 208.67.222.222
dnsIP: 8.8.8.8
dnsDOH: https://cloudflare-dns.com/dns-query
dnsDOT: cloudflare-dns.com